repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.49.0
    hooks:
      - id: typos
        args: []
        always_run: true
        pass_filenames: false
        priority: 0

  - repo: local
    hooks:
      - id: mix-format
        name: mix format --check-formatted
        entry: mix format --check-formatted
        language: system
        types_or: [elixir]
        pass_filenames: false
        priority: 0

      - id: credo
        name: mix credo --strict
        entry: mix credo --strict
        language: system
        types_or: [elixir]
        pass_filenames: false
        priority: 10

      - id: compile
        name: mix compile --warnings-as-errors
        entry: mix compile --warnings-as-errors
        language: system
        types_or: [elixir]
        pass_filenames: false
        priority: 0

      - id: dialyzer
        name: mix dialyzer
        entry: mix dialyzer
        language: system
        types_or: [elixir]
        pass_filenames: false
        priority: 10

      - id: test
        name: mix test --cover --warnings-as-errors
        entry: mix test --cover --warnings-as-errors
        language: system
        types_or: [elixir]
        pass_filenames: false
        priority: 10
