[tools]
elixir = "1.20.2-otp-29"
erlang = "29.0.3"
prek = "0.4.13"
typos = "1.49.0"

[tasks.dev]
description = "Start the development iex shell with history enabled"
run = [
  "iex --erl \"-kernel shell_history enabled\" -S mix"
]

[tasks.ci]
description = "Format, spell-check, lint, type-check, and run coverage tests"
depends = ["ci:format", "ci:typos", "ci:credo", "ci:dialyzer", "ci:test", "ci:docs"]

[tasks."ci:format"]
hide = true
run = "mix format"

[tasks."ci:compile"]
hide = true
run = "mix compile --warnings-as-errors"

[tasks."ci:typos"]
hide = true
run = "typos"

[tasks."ci:credo"]
hide = true
depends = ["ci:compile"]
run = "mix credo --strict"

[tasks."ci:dialyzer"]
hide = true
depends = ["ci:compile"]
run = "mix dialyzer"

[tasks."ci:test"]
hide = true
depends = ["ci:compile"]
run = "mix test --cover --warnings-as-errors"

[tasks."ci:docs"]
hide = true
depends = ["ci:compile"]
run = "mix docs"
