defmodule Mix.Tasks.ExParamsSchema.ExportJsonSchema do
  @shortdoc "Writes a defschema module as JSON Schema"

  @moduledoc """
  Outputs the JSON Schema generated by a module that uses `ExParamsSchema`.

      mix ex_params_schema.export_json_schema MyAppWeb.Params.CreateUser
      mix ex_params_schema.export_json_schema MyAppWeb.Params.CreateUser --output priv/schemas/create_user.json

  Without `--output`, the formatted JSON is written to standard output.
  """

  use Mix.Task

  @switches [output: :string]

  @impl Mix.Task
  def run(args) do
    Mix.Task.run("app.start")

    {options, module_names, invalid} = OptionParser.parse(args, strict: @switches)
    validate_arguments!(module_names, invalid)

    schema = module_names |> hd() |> schema_for_module!()
    json = Jason.encode!(schema, pretty: true)

    write_schema(json, options[:output])
  end

  @spec validate_arguments!([String.t()], [{String.t(), String.t() | nil}]) :: :ok
  defp validate_arguments!([_module_name], []), do: :ok

  defp validate_arguments!(_module_names, _invalid) do
    Mix.raise("usage: mix ex_params_schema.export_json_schema MODULE [--output PATH]")
  end

  @spec schema_for_module!(String.t()) :: map()
  defp schema_for_module!(module_name) do
    module = module_name |> String.split(".") |> Module.concat()

    unless Code.ensure_loaded?(module) do
      Mix.raise("could not load schema module #{inspect(module)}")
    end

    unless function_exported?(module, :json_schema, 0) do
      Mix.raise("#{inspect(module)} must define json_schema/0 through use ExParamsSchema")
    end

    module.json_schema()
  end

  @spec write_schema(String.t(), String.t() | nil) :: :ok
  defp write_schema(json, nil) do
    Mix.shell().info(json)
  end

  defp write_schema(json, output_path) do
    output_path |> Path.dirname() |> File.mkdir_p!()
    File.write!(output_path, json <> "\n")
    Mix.shell().info("Wrote JSON Schema to #{output_path}")
  end
end
